### ISSUE TITLE
Assert runtime invariant: all individuals in `MuPlusLambda::step` need to have a non-None index

### ISSUE THREAD

**Issue by jakobj** [Happy-Algorithms-League/hal-cgp#375]
The logic in `MuPlusLambda` (and likely in other places) assumes that all individuals in a population have been assigned a valid index. We should thus make sure of this in the beginning of this function using an `assert`.

**Comment by xueyongtu** [comment]
can't install this package in windows 10, use "python setup.py install" to install hal-cgp-0.3.0.tar.gz, please help me 

(base) D:\Download\hal-cgp-0.3.0>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    install_requires=read_requirements(),
  File "setup.py", line 25, in read_requirements
    with open("./requirements.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'

**Comment by xueyongtu** [comment]
I also tried other ways to install, all failed

**Comment by xueyongtu** [comment]
I deal with it by copying the requirements.txt into the file
